### PR TITLE
ENH: create extension and port to ITKv5

### PR DESCRIPTION
**Pull request by pieper**
This commit moves the LineMarkerRegistration module
into a subdirectory and also modernizes the code
with a few C++ 11 and ITK v5 updates.

Note that to avoid a build error related to std::vector
of bool on mac, ITK should include the following patch:
https://github.com/InsightSoftwareConsortium/ITK/pull/486/files

### CODE REVIEW

**Comment by pieper** [comment]
@tokjun this works on our local build, but requires an update to Slicer's ITK version before we can add it to the Slicer nightly build.

**Comment by pieper** [comment]
@tokjun the build issue related to ITKv5 seems to only occur on the Mac, and it will be resolved when Slicer gets updated (see issue referenced above).  While that update is pending, this code should still work on Windows and Linux, so I think we should merge this PR so we can start testing the extension in the nightly builds.

**Comment by pieper** [comment]
Hi @tokjun!  This is ready to merge now - Slicer has been updated to build the latest ITK 5.0.1, so this compiles on mac now.

**Comment by tokjun** [comment]
Sorry for the delay. Thanks @pieper !

**Pull request merged**
